name: employee_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3

  # Network & API
  http: ^1.2.0
  dio: ^5.4.0
  json_annotation: ^4.8.1

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # UI Components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6

  # Utils
  logger: ^2.0.2+1
  jwt_decoder: ^2.0.1
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/icons/logo.png
    
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700